[project]
name = "mtntripdata"
version = "0.1.0"
description = "Build a database of mountaineer activities by scraping data from mountaineer.org"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "neo4j>=5.0.0",
    "python-dotenv>=1.0.1",
    "rich>=13.9.4",
    "selenium>=4.29.0",
    "typer>=0.15.2",
]
