# 
# a postgres container and associated adminer container
#
name: mtndata

services:

  db:
    image: postgres
    container_name: db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - mountaineerdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: LetsClimb
      POSTGRES_DB: mountaineerdata
    ports:
     - 9010:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9011:8080

  neo4j:
    image: neo4j:2025.08
    container_name: neo4j
    restart: always
    volumes:
      - mountaineerneo4j:/data
    ports:
      - 9012:7687 # database
      - 9013:7474 # web interface
    environment:
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}

  # Deploy Cypher MCP Server
  mcp-neo4j-cypher-server:
    image: mcp/neo4j-cypher:latest
    ports:
      - '9014:9014'
    environment:
      - NEO4J_URI=bolt://host.docker.internal:9012
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD                # Empty it fills from the environment.
      - NEO4J_DATABASE=neo4j
      - NEO4J_TRANSPORT=http
      - NEO4J_MCP_SERVER_HOST=0.0.0.0 # must be 0.0.0.0 for sse  or http transport in Docker
      - NEO4J_MCP_SERVER_PORT=9014
      - NEO4J_MCP_SERVER_PATH=/api/mcp/
      - NEO4J_NAMESPACE=mountaineers
    depends_on:
      - neo4j

volumes:
  mountaineerdata:
  mountaineerneo4j:

